title: Site

sections:
  pages:
    label: gelistet
    type: pages
    layout: cards
    status: listed
    image:
      ratio: 1/1
      cover: true
  Drafts:
    type: pages
    layout: list
    status: drafts
  unpages:
    label: Ungelisted
    type: pages
    layout: list
    status: unlisted
  generell:
    type: fields
    fields:
      sitetitle:
        label: Seiten Titel
        type: text
      meta:
        type: textarea
        buttons: false
        width: 1/2
